: SAPIN ( -- ) CR 12 0 DO
  12 I - SPACES I 1+ DUP 0 DO [CHAR] / EMIT LOOP
  0 DO [CHAR] \ EMIT LOOP CR
  LOOP [CHAR] | DUP 2 0 DO
  12 0 DO [CHAR] ~ EMIT LOOP
  I 1 <> IF 2 0 DO EMIT LOOP THEN
  LOOP CR 12 SPACES 2 0 DO [CHAR] | EMIT
  LOOP 12 SPACES ;
SAPIN
\ FORGET SAPIN

